
name: Open Trade
on:
  schedule: [{cron: "0 * * * *"}]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: {python-version: "3.10"}
    - run: pip install pandas requests
    - run: python order_manager.py
      env:
        API_KEY: ${{ secrets.API_KEY }}
        USUARIO: ${{ secrets.USUARIO }}
        PASSWORD: ${{ secrets.PASSWORD }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        ACCOUNT_BALANCE: ${{ secrets.ACCOUNT_BALANCE }}
        RISK_PCT: ${{ secrets.RISK_PCT }}
        EPIC: ${{ secrets.EPIC }}
