name: Predict Daily

on:
  schedule:
    # Domingo apertura Forex
    - cron: "0 23 * * 0"
    # Lunes a jueves, 1 vez al día
    - cron: "0 0 * * 1-4"
    # Viernes última predicción
    - cron: "0 0 * * 5"
  workflow_dispatch:
