name: IG Trading Bot

on:
  schedule:
    - cron: "0,15,30,45 23 * * 0"
    - cron: "0,15,30,45 0-23 * * 1-4"
    - cron: "0,15,30,45 0-20 * * 5"
  workflow_dispatch:


jobs:
  trade:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: pip install requests
      - name: Run bot
        run: python trade.py
        env:
          IG_API_KEY: ${{ secrets.API_KEY }}
          IG_USERNAME: ${{ secrets.USUARIO }}
          IG_PASSWORD: ${{ secrets.PASSWORD }}
